name: pokeflutter
description: Mi Pokédex con Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.0
  # dio: ^5.7.0                      (HTTP — Sesión 7)
  # go_router: ^14.0.0               (Navegación — Sesión 4)
  # shared_preferences: ^2.3.0       (Favoritos locales — Sesión 6)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
